backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "images/uploads"

collections:
  # - name: "post" # Used in routes, e.g., /admin/collections/post
  #   label: "Post"
  #   folder: "_posts" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   fields:
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "page"
    label: "Page"
    folder: "_pages"
    create: true
    slug: ".md"
    fields:
      - {label: "Layout", name: "layout", widget: "select", options: ["about", "blog", "contact", "gallery", "page"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "//"}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  # - name: "layouts"
  #   label: "Layouts"
  #   folder: "_layouts"
  #   extension: "html"
  #   fields:
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
  #     - {label: "Title", name: "title", widget: "string", required: false}
  #     - {label: "Body", name: "body", widget: "markdown", required: false}